os: osx

addons:
  homebrew:
    packages:
        - zig
        - coreutils # gtimeout
    casks:
      - textmate
    # workaround for issue: https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/10
    update: true

script: |
  set -e
  . .github/workflows/test.sh
