name: textmate
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          brew cask install textmate
          brew install coreutils zig
      - name: Textmate load success
        run: |
          set -e
          . .github/workflows/test.sh