name: textmate
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Textmate load success
        run: |
          set -vx
          brew cask install textmate

          # "install" bundle
          mkdir -p "$HOME/Library/Application Support/TextMate/Bundles/"
          ln -s $PWD "$HOME/Library/Application Support/TextMate/Bundles/Zig.tmbundle"

          /Applications/TextMate.app/Contents/MacOS/TextMate | tee textmate.out &
          
          # give TextMate some time to load
          sleep 3
          
          # don't expect the bundle to be mentioned here as that would indicate an error
          ! grep Zig.tmbundle textmate.out
          
          # open source, use build macro from zig bundle to build and text executable
          mate hello.zig
          osascript -e 'activate application "TextMate"'
          osascript -e 'tell application "TextMate" to quit'
          sleep 3
          ls -l hello
          ./hello